# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9bf738bb8ac43c4f106bc17697d651ba00dc94f9b2156a839135ff9d8185824609053f476c3f21a46579b5bc4d61a74b1a9dc47d6e4e5243ebdcf186eee4679

test:
  secret_key_base: 25591fb6ac0d3119a5546874e3182f0f8613e5c121baab511f8a6e184ed623e13ba4a24a9a865b999915a31f531189abbc70e455f522485cf5ef8f9f08657313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
